# Bill Scan Service Configuration
server:
  port: 8089

spring:
  application:
    name: billscan-service
  datasource:
    url: jdbc:postgresql://${database.host}:${database.port}/${database.name}_billscan
    username: ${database.username}
    password: ${database.password}
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect

# Eureka client configuration
eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/
  instance:
    prefer-ip-address: true

# Service specific configuration
billscan:
  ocr:
    provider: tesseract
    language: eng
    confidence-threshold: 0.8
  image:
    max-size: 10485760  # 10MB
    allowed-formats:
      - jpg
      - jpeg
      - png
      - pdf
  processing:
    queue-size: 1000
    batch-size: 10
    timeout: 30000  # 30 seconds
  validation:
    required-fields:
      - invoice_number
      - total_amount
      - date
    optional-fields:
      - tax_amount
      - vendor_name

management:
  endpoints:
    web:
      exposure:
        include: health,info,metrics
  endpoint:
    health:
      show-details: always
