# Inventory Service Configuration
server:
  port: 8083

spring:
  application:
    name: inventory-service
  datasource:
    url: jdbc:postgresql://${database.host}:${database.port}/${database.name}_inventory
    username: ${database.username}
    password: ${database.password}
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect

# Eureka client configuration
eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/
  instance:
    prefer-ip-address: true

# Service specific configuration
inventory:
  low-stock:
    threshold: 10
    alert-enabled: true
  reorder:
    point: 5
    quantity: 50
  batch:
    tracking:
      enabled: true
    expiry:
      alert-days: 30
  warehouse:
    locations:
      - Main Warehouse
      - Branch A
      - Branch B

management:
  endpoints:
    web:
      exposure:
        include: health,info,metrics
  endpoint:
    health:
      show-details: always
