# Medicine Service Configuration
server:
  port: 8082

spring:
  application:
    name: medicine-service
  datasource:
    url: jdbc:postgresql://localhost:5432/medvix_medicines
    username: postgres
    password: admin
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect

# JWT Configuration
jwt:
  secret: medvix-jwt-secret-key-for-user-service-authentication-2025

# Eureka client configuration
eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/
  instance:
    prefer-ip-address: true

# Service specific configuration
medicine:
  validation:
    name:
      min-length: 3
      max-length: 100
    price:
      min-value: 0.01
    expiry-date:
      future-only: true
  search:
    default-page-size: 20
    max-page-size: 100
  categories:
    - Prescription
    - Over-the-counter
    - Generic
    - Branded

management:
  endpoints:
    web:
      exposure:
        include: health,info,metrics,refresh,gateway
  endpoint:
    health:
      show-details: always
