# User Service Configuration
server:
  port: 8001

spring:
  application:
    name: user-service
  cloud:
    gateway:
      routes:
        - id: user-service
          uri: http://localhost:8081
          predicates:
            - Path=/api/auth/**
            - Path=/api/users/**
  datasource:
    url: jdbc:postgresql://localhost:5432/medvix_user
    username: postgres
    password: admin
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        format_sql: true
  data:
    redis:
      host: localhost
      port: 6379
      timeout: 2000ms
  mail:
    host: smtp.gmail.com
    port: 587
    username: m29400511@gmail.com
    password: medvix1234
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true
  rabbitmq:
    host: localhost
    port: 5672
    username: guest
    password: guest

# JWT Configuration
jwt:
  secret: medvix-jwt-secret-key-for-user-service-authentication-2025
  expiration: 86400000
  refresh-expiration: 604800000

# Security Configuration
security:
  jwt:
    header: Authorization
    prefix: Bearer

# Eureka client configuration
eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/
  instance:
    prefer-ip-address: true

# Application specific configuration
app:
  frontend:
    url: http://localhost:3000

management:
  endpoints:
    web:
      exposure:
        include: health,info,metrics,refresh
  endpoint:
    health:
      show-details: always

# Logging
logging:
  level:
    com.medivex.user.service: DEBUG
    org.springframework.security: DEBUG
    org.springframework.web: DEBUG
