# User Service Configuration
server:
  port: 8081

spring:
  application:
    name: user-service
  datasource:
    url: jdbc:postgresql://${database.host}:${database.port}/${database.name}_users
    username: ${database.username}
    password: ${database.password}
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
  redis:
    host: ${redis.host}
    port: ${redis.port}
    password: ${redis.password}

# Eureka client configuration
eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/
  instance:
    prefer-ip-address: true

# Service specific configuration
user:
  jwt:
    secret: ${jwt.secret}
    expiration: ${jwt.expiration}
  password:
    min-length: 8
    require-special-chars: true
  session:
    timeout: 1800  # 30 minutes

management:
  endpoints:
    web:
      exposure:
        include: health,info,metrics
  endpoint:
    health:
      show-details: always
